### ISSUE TITLE
altitude visualization

### ISSUE THREAD

**Issue by wilco1967** [stronnag/bbl2kml#8] opened 2021-01-03 13:45 UTC
Hi Jonathan,

Great piece of software again. Works beautifully.
Hope you don't mind me some nitpicking....

I fly in pretty flat surroundings (NL), but still happend to notice some strange behaviour.
I flew a WP mission, with long stretches of same altitude, but when plotting the mission, I noticed the track seemed to follow the landscape elevation below. 
Although the actual landscape is flat, the reported elevation in google earth seems to pick up treetop hights occasionally, so it shows some 'hill', while there is actually nothing below (just a small wooded area).

The mission was flown at mostly 75 meter, and in the dot description, it is reported as precisely 75 meters, but still the dot's are drawn slightly higher / lower, following the ground elevation below.

iNav reported highed is relative to launch elevation, but somehow, google earth shows if following the landscape elevation while in fact it flew constant elevation. 

If I plot the same flight, from the OTx log, and show it in google earth (using openTx companion logviewer), it shows a nice even elevation, but consistantly below the BBL/kmz file. 

![elevation](https://user-images.githubusercontent.com/4282983/103480030-1bcfb480-4dd2-11eb-982f-1ff3c52ae57c.jpg)

I'm guessing, google earth plots the points relative to ground level ?
Perhaps we'll have to plot them absolute, and recalculate each point elevation, to the ground elevation at the arming point (not current position) ?
Also, use the arming elevation, not the (safe)home point (which, btw, is shown correctly)

the -elev options didn't seem to make any difference.

Using windows 10, iNav 2.5.1 (older flightlog), MatekF722

BTW, it would be nice if you could add a (grey) ground track below.

Anyway, a very nice tools.... especially for flight outside of radio range (i.e. without OTx log).

attached, the 'offending' BBL file
[LOG00074.TXT](https://github.com/stronnag/bbl2kml/files/5761665/LOG00074.TXT)

**Comment by stronnag** [comment] 2021-01-03 13:53
You're correct, I'm not compensating for the elevation correctly. As I think we discussed, I fly at a fairly flat part of the world too, so I didn't notice it. 

I just need to get the home elevation (which I have from the BBL), and set set absolute, as you noted. In progress.

**Comment by stronnag** [comment] 2021-01-03 13:55
And I will add the ground track .... to damn cold to go flying.

**Comment by wilco1967** [comment] 2021-01-03 14:09
thanks....

I guess, 'home' elevation in the BBL is just 0 ?

**Comment by wilco1967** [comment] 2021-01-03 14:11
sorry..... wrong button....

Isn't the home elevation always 0, or does iNav log the absolute (GPS) altitude as well ?
anyway, it should be the elevation when arming. The 'home' position could also be a safehome.

**Comment by stronnag** [comment] 2021-01-03 14:19
We have GPS altitude in the BBL, which I'll take from arming location.

**Comment by stronnag** [comment] 2021-01-03 14:19
btw what OS (MacOS/Linux/Windows) would you wish to test on?

**Comment by wilco1967** [comment] 2021-01-03 14:28
I got win10

**Comment by stronnag** [comment] 2021-01-03 15:34
So this looks better? Constant level over the only hill in the whole country? Nice bit of quarry diving.

![Screenshot-20210103153232-894x314](https://user-images.githubusercontent.com/158229/103482500-204b9b80-4dd9-11eb-8a4d-a621b4efc98b.png)

**Comment by wilco1967** [comment] 2021-01-03 15:51
yeah, that looks good.....

This was the last of a couple of missions, to see how low I could reliably go, without crashing into some obstacles, in WP mode.... (below surrounding area ground level, out of radio range).
Judging from the video, perhaps can go 5 meters lower, and still make it back..... But if it fails, very difficult retrieving it from the quarry, so maybe better not try again.... ;-)

**Comment by stronnag** [comment] 2021-01-03 15:53
here's  a win10 binary with the fix

[bbl2kml-0.2.0+i8.zip](https://github.com/stronnag/bbl2kml/files/5761817/bbl2kml-0.2.0%2Bi8.zip)

**Comment by wilco1967** [comment] 2021-01-03 16:38
alright, that seems to work excellent !
The terain 'following' effect is gone. 

But there still is a offset in elevation between the OTx log, and the BBL log, of which looks like an (estimated) 10 meters, which I cannot explain.

This may be an error on OTx log side, as upon landing, the OTx log seems to go 'underground' a few meters.... However, on takeoff, the OTx altitude seems correct.

upon takeoff, both altitudes are the same, but as the plane climbs out, they start to deviate, BBL showing higher as OTx. This deviation remains constant over the flight.
![elevation2](https://user-images.githubusercontent.com/4282983/103483363-1892f380-4de7-11eb-9e0a-321767f4c98f.jpg)

Probably a google / OpenTX quirk..... 

The BBL log shows the last few points dropping from +1 to -3 meter after landing, when it already has come to a stop. Guess thats because the GPS alt at landing seems to be 3 meters below that at takeoff (small GPS drift, as it is actually flat).
   
The OTx log also shows a GPS alt upon landing to be 3 meters below the takeoff alt. The (indicated, relative) alt keeps dropping another 3 meters, after hitting the ground (as seen from the groundspeed dropping off). Guess this has to do with the relative slow GPS alt update. 

Anyway, nothing to worry about. just trying to understand what I'm looking at.

Great tool, Thanks a lot again !

**Comment by wilco1967** [comment] 2021-01-03 17:14
one more minor thing.....
3D cruise is shown as 'angle' mode...... 
Well, guess it is some kind of angle mode, but with a difference.

also, manual mode has the same colour as angle (actually, 3CRS).

**Comment by stronnag** [comment] 2021-01-03 17:20
angle and manual are the same colour as they are not navigation modes, 3CRS should be purple ... 
As the way nav modes are defined in BBL has changed 6 time is inav's history, this is non-trivial to get right. Eventually.

**Comment by stronnag** [comment] 2021-01-03 17:21
But many thanks for the report, please keep them coming.

**Comment by stronnag** [comment] 2021-01-03 20:47
I spent a little while reconciling your BBL and OTX log, in terms of usefulness, there really is no comparison. BBL wins easily. It's actually somewhat difficult to compare them in that the time-stamps different; the BBL logs are stamped with the GPS time, the OTX log possibly with the time from TX. so jcomparing the OTX entry for BBL time 'T' results in locations that are 100s of metres apart. As both times are clock times, I'd hoped that at any given time, the locations would be close; they are not. 

Here's a few images from a real GIS (Quantum GIS). 

Here's both the images together, note that there are OTX (red) points well away from the seeming smooth BBL (green) track.
![Screenshot-20210103203228-1506x744](https://user-images.githubusercontent.com/158229/103488337-97962500-4e03-11eb-9191-f625bc6d4887.png)

The OTX
![Screenshot-20210103203326-1487x741](https://user-images.githubusercontent.com/158229/103488373-d926d000-4e03-11eb-961d-9c8a7015662c.png)

The BBL 
![Screenshot-20210103203247-1518x725](https://user-images.githubusercontent.com/158229/103488467-987b8680-4e04-11eb-914d-0fd40117450a.png)


I know which I'd trust; it's not the OTX.

Hope that makes sense, it's been a useful exercise.

**Comment by stronnag** [comment] 2021-01-03 21:11
It gets better ....

I've now updated both `bbl2kml` and `otx2kml` to use altitudes correctly and I loaded your BBL and OTX into Google Earth. In order to make a visual comparison, the BBL log is in RSSI mode (red dots as you have good RSSI) and the OTX log is in flight mode (blue, yellow, purple white). 

You can see the image; I think the correlation is pretty good (not withstanding my condemnation of OTX data above). Locations and altitudes appear consistent.

I also note that the OTX KML has purple (3CRS) tracks, and the BBL doesn't. That's the next challenge.
But overall, I think it's looking OK.

![Screenshot-20210103210532-1328x667](https://user-images.githubusercontent.com/158229/103488863-2442e200-4e08-11eb-9c32-2dcefb4aa584.png)

**Comment by stronnag** [comment] 2021-01-03 21:12
KMZ files for comparison.
[kmz.zip](https://github.com/stronnag/bbl2kml/files/5762301/kmz.zip)

**Comment by stronnag** [comment] 2021-01-03 22:02
Yeah! found and fixed the CRS regression. The following should work correctly. Note that the OTX converter currently needs 
```
-home-alt ALT
```
which for your example is 
```
otx2kml -home-alt 34 Talon_1-2020-11-07.csv
```

This will be automated tomorrow, either from Galt(m) in the log if available, or an online lookup if not.
Windows binaries:

[bbl2kml-0.2.0+#8A-win32.zip](https://github.com/stronnag/bbl2kml/files/5762340/bbl2kml-0.2.0%2B.8A-win32.zip)

Thanks as ever for some excellent test materials!

**Comment by wilco1967** [comment] 2021-01-04 12:10
Hi Jonathan,

Seems like both OTx and BBL are overlapping, after both processing with your tool.
Still, when plotting the OTx file, using OpenTx companion, there is a slight offset in elevation. About 10 meters I guess.

As it it based on exactly the same logfile, something is different in how your tool converts it to kml, and how OpenTx Companion exports the kml..... not a huge difference, but still noticable....

As mentioned before, It may well be OTx companion that is 'wrong'.... just curious why if is different.

Sure, the BBL is much more reliable, as it is recorded on-board. OTx logfiles suffer from signal loss, and time differences....
Not releated to your tool, but somehow, OTx doesn't want to update the transmitter time based on the GPS time as received through telemetry.... It is supposed to work, but it never did (at least, not for me).
Anyway, that doesn't matter so much..... it is the positions that overlap, not the timestamps.
Still, if the plane ever fails to return, the OTx log may be all that I have....

**Comment by stronnag** [comment] 2021-01-04 14:50
OK, there is new issue for the ground track, I think everything else is addressed (altitude mode, cruise colour), otx home altitude), so let's close this one. Thanks for the samples and commentary.

**Closed by stronnag** 2021-01-04 14:50 UTC
Labels: bug

**Comment by skorokithakis** [comment] 2021-01-04 19:25
As an aside, I don't think a straight-up comparison between OTX and BBL is entirely warranted because, for many people (me included), BBL is so inconvenient that I would basically only do it when I suspect an issue, whereas OTX logging I can just leave on for every flight. For some of my planes, I need to remove the FC to access the SD card, and I don't want to permanently leave N SD cards in all the model, so usually for me the option is "OTX logging or nothing", where the former easily wins.
